title: La Cordonie
description: >- # this means to ignore newlines until "baseurl:"
  Une page dev & chill
baseurl: ""
url: "https://lacordony.github.io"
github_username: lacordony
locale: fr_FR

# Build settings
sass:
    sass_dir: _sass
    style: compressed
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: "assets/img/social/social-logo-full.png"

kramdown:
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
